export type Category = {
  name: string;
  color: string;
  activities: string[];
};

export const categories: Category[] = [
  {
    name: "Indoor / Self-play",
    color: "bg-violet-100 text-violet-800 border-violet-200",
    activities: [
      "Piano (practice)",
      "Ukulele (practice)",
      "Violin (practice)",
      "Audio (music / stories)",
      "Puzzles",
      "Role-play (dolls / barn / trucks)",
      "Dress up",
      "Coloring",
      "Paper Arts (cut-outs, origami, airplanes)",
      "Water Wow / magic screen",
      "Watercolors",
      "Sculpting (play-doh / clay / kinetic sand)",
      "Building (lego / magnets / abacus)",
      "Cosmic Yoga",
    ],
  },
  {
    name: "Active & Outdoor",
    color: "bg-green-100 text-green-800 border-green-200",
    activities: [
      "Walk",
      "Park / Visit",
      "Gymnastics bar",
      "Ju Jitsu",
      "Swim",
      "Yard / Garden work",
      "Trampoline",
      "Fort building",
      "Gymnastics",
      "Bike / Scooter",
      "Tennis",
    ],
  },
  {
    name: "Creative & Sensory",
    color: "bg-pink-100 text-pink-800 border-pink-200",
    activities: [
      "Drawing / Art",
      "Acrylics",
      "Rainbow scratch",
      "Alien draw",
      "Color by number",
      "Stencils",
      "Lite-Brite",
      "Sewing",
      "KiwiCrate",
    ],
  },
  {
    name: "Books & Reading",
    color: "bg-amber-100 text-amber-800 border-amber-200",
    activities: [
      "Dad read-aloud",
      "Self-reading",
      "Large picture books",
      "Audio stories",
      "Leapfrog Pen books",
    ],
  },
  {
    name: "Games",
    color: "bg-sky-100 text-sky-800 border-sky-200",
    activities: [
      "Chess (with partner)",
      "Chess — learning app",
      "Checkers",
      "Connect-4",
      "Pokémon",
      "Bingo",
      "Boardgames",
      "Simon Says",
      "Story cards",
      "Word search",
      "Create mazes / puzzles",
      "Pretend play",
      "Family photo viewing",
    ],
  },
  {
    name: "Digital & Screen",
    color: "bg-indigo-100 text-indigo-800 border-indigo-200",
    activities: [
      "IXL",
      "Art Kids Hub",
      "Coding apps",
      "Video games",
      "TV / Show",
      "iPad games",
    ],
  },
  {
    name: "Academic / With Guidance",
    color: "bg-teal-100 text-teal-800 border-teal-200",
    activities: [
      "Math",
      "Beast Academy",
      "Math rods",
      "Workbooks",
      "Story writing",
      "Essay writing",
      "Poem",
      "Drama / script",
      "Spanish",
      "Violin (lesson)",
      "Piano (lesson)",
      "MagnifiKid",
      "Moon Journaling",
      "Experiments",
      "Coding (instructional)",
    ],
  },
  {
    name: "Food",
    color: "bg-orange-100 text-orange-800 border-orange-200",
    activities: ["Breakfast", "Snack", "Lunch", "Dinner", "Smoothie"],
  },
  {
    name: "Routine & Reset",
    color: "bg-rose-100 text-rose-800 border-rose-200",
    activities: [
      "Make bed",
      "Bath",
      "Relaxation activity",
      "Cleaning house",
      "Cooking",
      "Sleep prep",
    ],
  },
  {
    name: "Outings & Errands",
    color: "bg-lime-100 text-lime-800 border-lime-200",
    activities: [
      "Duke Park",
      "Watts",
      "East Campus",
      "Ninth St",
      "Hunky Dory",
      "Bulldega",
      "Cocoa Cinnamon",
      "Fullsteam",
      "Mass",
      "Car errands",
      "Home Depot",
      "Roscoe Bath",
    ],
  },
];
